modLoader = "javafml"
loaderVersion = "[1,)"
license = "Stardust Labs License"
[[mods]]
modId = "incendium"
version = "5.3.4"
displayName = "Incendium"
displayURL = "https://www.stardustlabs.net/"
logoFile = "pack.png"
authors = "Stardust Labs"
description = "Incendium ~ Nether Expansion (v5.3.4 for 1.20-1.20.4)"

[dependencies]
[[dependencies.incendium]]
modId = "forge"
mandatory = false
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.incendium]]
modId = "neoforge"
mandatory = false
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.incendium]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

